config/routes.rb
Rails.application.routes.draw do
  get 'translations/index'


  get 'pages/landing_page'


  # oauth endpoints
  get '/auth/:provider/callback', to: 'admin/sessions#create'
  get 'auth/failure', to: redirect('/edit/sessions/new')


  namespace 'edit', module: 'admin', as: 'admin' do
    resources :contents

    resources :translations, constraints: { :id => /[^\/]+/ }

    # authentication management
    get 'sessions/new'
    get 'sessions/destroy'
    delete 'signout', to: 'sessions#destroy', as: 'signout'

    get '/', to: 'pages#index'
  end

  root 'pages#landing_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/user.rb
class NotRegisteredError < StandardError ; end
class NoAdminRoleError < StandardError ; end
class UnallowedDummyUserAccessError < StandardError ; end

class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      # user.save!
    end

    Rails.logger.debug user.inspect

    raise NotRegisteredError.new('the given user is not in the database') unless user
    raise NoAdminRoleError.new('You don\'t have the appropriate rights to access these resources') unless user.admin?

    return user
  end

  def self.dummy_user
    unless Rails.env.production?
      User.new.tap do |user|
        user.id = 1
        user.email = 'dummy@user.de'
        user.uid = 12345
        user.provider = 'godhub'
        user.avatar_url = 'https://fthmb.tqn.com/tVtfXU4sqXsVY2_4CMsSX9XbpeA=/768x0/filters:no_upscale()/about/spongebob_wide-56a00f0a5f9b58eba4aeb6f2.jpg'
        user.username = 'Spunchy'
        user.admin = true
      end
    else
      raise UnallowedDummyUserAccessError.new('dummy user is not allowed in production')
    end
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ::ActionController::Base
  protect_from_forgery with: :exception
  before_action :reject_unauthenticated
  before_action :find_locale
  helper_method :current_user

  layout 'admin_layout'

  private

  def find_user(user_id)
    Rails.env.production? ? User.find(session[:user_id]) : User.dummy_user
  end


  def current_user
    session[:user_id].nil? ? nil : find_user(session[:user_id])
  end

  def admin?
    current_user.admin?
  end

  def reject_unauthenticated
    redirect_to admin_sessions_new_path unless (current_user && admin?)
  end

  def find_locale
    @locale = params[:locale_id] || I18n.locale
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < Admin::ApplicationController
  before_action :set_content, only: [:show, :edit, :update]

  # edit landing_page
  def index
    @contents = Content.all
  end

  def show
  end

  # GET /fubars/1/edit
  def edit
  end

  def update
    if @content.update(content_params)
      redirect_to @content, notice: 'Fubar was successfully updated.'
    else
      render :edit
    end
  end


  private

  def set_content
    @content = Content.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:body)
  end

  def content_url(content)
    edit_admin_content_url(content)
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::ApplicationController
  # edit landing_page
  def index
    @welcome_text = Content.find_or_create_by(name: 'landing_page_welcome_text')
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ::Admin::ApplicationController
  skip_before_action :reject_unauthenticated

  def new
    session[:user_id] = User.dummy_user.id unless Rails.env.production?
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/admin/translations_controller.rb
class Admin::TranslationsController < ::Admin::ApplicationController
  before_action :find_locale
  before_action :retrieve_key, only: [:create, :update]
  before_action :find_translation, only: [:edit, :update]

  def index
    @translations = Translation.locale(@locale)
  end

  def new
    @translation = Translation.new(locale: @locale, key: params[:key])
  end

  def create
    @translation = Translation.new(translation_params)
    if @translation.value == default_translation_value
      flash[:alert] = "Your new translation is the same as the default."
      render :new
    else
      if @translation.save
        flash[:success] = "Translation for #{ @key } updated."
        I18n.backend.reload!
        redirect_to admin_translations_url(@locale)
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @translation.update(translation_params)
      flash[:notice] = "Translation for #{ @key } updated."
      I18n.backend.reload!
      redirect_to admin_translations_url(@locale)
    else
      render :edit
    end
  end

  # def destroy
  #   Translation.destroy(params[:id])
  #   I18n.backend.reload!
  #   redirect_to admin_translations_url(@locale)
  # end

  private

  def find_translation
    @translation = Translation.find(params[:id])
  end

  def retrieve_key
    @key = params[:i18n_backend_active_record_translation][:key]
  end

  def translation_params
    params.require(:i18n_backend_active_record_translation).permit(:locale,
      :key, :value)
  end

  def default_translation_value
    I18n.t(@translation.key, locale: @locale)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
    @welcome_text = Content.find_by(name: "landing_page_welcome_text")
    render layout: 'landing_page'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    return markdown_renderer.render(text).html_safe
  end

  private

  def markdown_renderer
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      autolink: true,
      tables: true,
      underline: true,
      highlight: true
    )
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
  def translation_keys(i18n_locale)
    I18n.backend.translations_store(i18n_locale)
  end

  def prefixed_translation_keys(locale, prefix)
    translation_keys(locale).select { |k| !k.nil? && k.starts_with?(prefix)  }
  end

  def price_category_translations(locale)
    prefixed_translation_keys(locale, 'price-categories')
      .select { |key| !key.nil? && !(key.ends_with?('.currency') || key.ends_with?('.special') || key.ends_with?('.items')) }
  end


  private

  # def en_keys
  # end

  # def de_keys
  #   [ "landing-page.edit.welcome_text", "site_description", "contact_name" ]
  # end

  # def default_keys
  #   [
  #     "landing-page.prices.headline",
  #     "price-categories.first-try.headline",
  #     "price-categories.first-try.sub-headline",
  #     "price-categories.first-try.offers.trial.headline",
  #     "price-categories.first-try.offers.trial.price",
  #     "price-categories.first-try.offers.new-customer-1.headline",
  #     "price-categories.first-try.offers.new-customer-1.price",
  #     "price-categories.first-try.offers.new-customer-1.info",
  #     "price-categories.first-try.offers.new-customer-2.headline",
  #     "price-categories.first-try.offers.new-customer-2.price",
  #     "price-categories.first-try.offers.new-customer-2.info",
  #   ]
  # end

  def translation_for_key(translations, key)
    hits = translations.to_a.select{ |t| t.key == key }
    hits.first
  end
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Admin Area</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Landing-Page <span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
  </div>
</nav>

app/views/admin/contents/_form.html.erb
<%= form_for content, url: admin_content_path(content), html: { class: 'content-form' } do |f| %>

  <div class="card-block">
    <div class="form-group">
      <preview-text-area language="markdown">
        <%= f.text_area :body, rows: 20 %>
      </preview-text-area>
    </div>
  </div>

  <footer class="card-footer">
    <%= f.submit "Speichern" %>
  </footer>

<% end %>

app/views/admin/contents/edit.html.erb
<%= render 'form', content: @content  %>

app/views/admin/contents/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Inhalt</th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= content.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/index.html.erb
<div class="card">
  <div class="card-header">
    <h3><%= t('landing-page.edit.welcome_text') %></h3>
  </div>
  <embed-form selector=".content-form">
    <%= render 'admin/contents/form', content: @welcome_text %>
  </embed-form>
</div>

<div class="card">
  <div class="card-header">
    <h3><%= t('landing-page.edit.price-category-translations') %></h3>
  </div>

  <%= render partial: 'admin/translations/translation_key_list', locals: { translations: price_category_translations(@locale) } %>
</div>

app/views/admin/translations/_translation_key_list.html.erb
<table>
  <thead>
    <tr>
      <th>Translation Key</th>
      <th>Setting</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% translations.each do |key| %>
      <% translation = translation_for_key(@translations, key) %>
      <tr id="<%= key %>">
        <td><%= key %></td>
        <td><%= translation.nil? ? I18n.t(key, locale: @locale) : translation.value %></td>
        <td>
          <% if translation.nil? %>
            <%= link_to "Edit", new_admin_translation_url(@locale, key: key) %>
          <% else %>
            <%= link_to "Edit", edit_admin_translation_url(translation, @locale) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/translations/create.html.erb
<h1>Translations#create</h1>
<p>Find me in app/views/translations/create.html.erb</p>

app/views/admin/translations/edit.html.erb
<%= form_for @translation, url: admin_translation_path do |form| %>
  <%= form.label :locale %> <%= form.text_field :locale, readonly: true %>
  <%= form.label :key %> <%= form.text_field :key, readonly: true %>
  <%= form.label :value %> <%= form.text_area :value %>

  <%= form.submit 'Save Translation' %> <%= link_to "Cancel", admin_translations_url(@locale) %>
<% end %>

app/views/admin/translations/index.html.erb
<h1>Translations for <%= @locale %></h1>

<%= render partial: 'admin/translations/translation_key_list', locals: { translations: translation_keys(@locale) } %>

app/views/admin/translations/new.html.erb
<%= form_for @translation, url: admin_translations_path do |form| %>
  <%= form.label :locale %> <%= form.text_field :locale, readonly: true %>
  <%= form.label :key %> <%= form.text_field :key, readonly: true %>
  <%= form.label :value %> <%= form.text_area :value, value: I18n.t(@translation.key, locale: @locale) %>

  <%= form.submit 'Save Translation' %> <%= link_to "Cancel", admin_translations_url(@locale) %>
<% end %>

app/views/admin/translations/update.html.erb
<h1>Translations#update</h1>
<p>Find me in app/views/translations/update.html.erb</p>

app/views/landing_page/_price_category.html.erb
<price-category>
  <header>
    <h3><%= headline %></h3>
    <p class="sub-headline"><%= sub_headline %></p>
  </header>

  <% (items || []).each do |item| %>
    <%= render partial: 'landing_page/price_item', locals: { item: item } %>
  <% end %>
</price-category>

app/views/landing_page/_price_item.html.erb
<price-item <%= I18n.exists?("price-categories.#{item}.special", locale) ? "special" : nil %>>
  <h4><%= t("price-categories.#{item}.headline") %></h4>

    <% unless I18n.exists?("price-categories.#{item}.items", locale) %>

      <%= render partial: 'landing_page/price_offer', locals: { item: item, priceItem: nil } %>

    <% else %>

      <% t("price-categories.#{item}.items").each do |priceItem| %>
        <%= render partial: 'landing_page/price_offer', locals: { item: item, priceItem: priceItem } %>
      <% end %>

    <% end %>
</price-item>

app/views/landing_page/_price_offer.html.erb
<price-offer>
  <price-value>
    <%= number_to_currency((priceItem.nil? ? t("price-categories.#{item}.price") : priceItem[:price]), {
        locale: :de,
        precision: t("price-categories.#{item}.precision").to_i
      }) %>

    <price-currency><%= t("price-categories.#{item}.currency") %></price-currency>


    <price-offer-meta <%= I18n.exists?("price-categories.#{item}.rhythm", locale) ? "indent" : nil %>>
      <% if I18n.exists?("price-categories.#{item}.rhythm", locale) %>
          <offer-meta-rhythm><%= t("price-categories.#{item}.rhythm") %></offer-meta-rhythm>
      <% end %>

      <% if I18n.exists?("price-categories.#{item}.info", locale) || (priceItem && priceItem[:info]) %>
        <offer-meta-sub-headline><%= priceItem.nil? ? t("price-categories.#{item}.info") : priceItem[:info] %></offer-meta-sub-headline>
      <% end %>
    </price-offer-meta>
  </price-value>


  <% if I18n.exists?("price-categories.#{item}.long-info", locale) %>
    <p><%= raw t("price-categories.#{item}.long-info") %></p>
  <% end %>
</price-offer>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy Yoga - Admin Area</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous" defer></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous" defer></script>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'admin_bundle', 'data-turbolinks-track': 'reload', defer: 'true' %>

  </head>

  <body>
    <%= render 'admin/navbar'  %>
    <main class="container-fluid">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy Yoga</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous" defer></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application_bundle', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<% content_for :content do %>
  <div class="container-fluid layout layout-landing-page">
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/pages/landing_page.html.erb
<content-block name="welcome-text">
  <content-block-body>
    <%= markdown(@welcome_text.body) %>
  </content-block-body>
</content-block>

<content-block name="price-list">
  <content-block-body>
    <h2><%= t('landing-page.prices.headline') %></h2>

    <%= render partial: 'landing_page/price_category', locals: {
      headline: t('price-categories.first-try.headline'),
      sub_headline: t('price-categories.first-try.sub-headline'),
      items: %w(first-try.offers.trial first-try.offers.new-customer-1 first-try.offers.new-customer-2)
    } %>

    <%= render partial: 'landing_page/price_category', locals: {
      headline: t('price-categories.time-cards.headline'),
      sub_headline: t('price-categories.time-cards.sub-headline'),
      items: %w(time-cards.offers.single time-cards.offers.quadruple time-cards.offers.decuple time-cards.offers.decuple-long)
    } %>

    <%= render partial: 'landing_page/price_category', locals: {
      headline: t('price-categories.flatrates.headline'),
      sub_headline: t('price-categories.flatrates.sub-headline'),
      items: %w(flatrates.offers.full-year flatrates.offers.half-year flatrates.offers.month)
    } %>

    <%= render partial: 'landing_page/price_category', locals: {
      headline: t('price-categories.abo.headline'),
      sub_headline: t('price-categories.abo.sub-headline'),
      items: %w(abo.offers.full-year)
    } %>
  </content-block-body>
</content-block>